CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION public.annual_audit_sha256(value text)
RETURNS char(64) LANGUAGE sql IMMUTABLE STRICT PARALLEL SAFE AS $$
  SELECT encode(digest(value, 'sha256'), 'hex')::char(64);
$$;

CREATE OR REPLACE FUNCTION public.annual_audit_set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.ata_schema_migration (
  version varchar(64) PRIMARY KEY,
  description varchar(255) NOT NULL,
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.audit_engagement (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  engagement_code varchar(64) NOT NULL UNIQUE,
  name varchar(255) NOT NULL,
  engagement_type varchar(64) NOT NULL DEFAULT 'annual_financial_statement_audit',
  entity_name varchar(255) NOT NULL, entity_uscc varchar(64),
  fiscal_year smallint NOT NULL, period_start date NOT NULL, period_end date NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'planning', company_id varchar(128) NOT NULL DEFAULT '',
  owner_user_id varchar(128) NOT NULL DEFAULT '', created_by varchar(128) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_audit_engagement_period ON public.audit_engagement (fiscal_year, period_end);
CREATE INDEX IF NOT EXISTS idx_audit_engagement_status ON public.audit_engagement (status, deleted_at);
CREATE INDEX IF NOT EXISTS idx_audit_engagement_company ON public.audit_engagement (company_id, deleted_at);
CREATE INDEX IF NOT EXISTS idx_audit_engagement_owner ON public.audit_engagement (owner_user_id, deleted_at);

CREATE TABLE IF NOT EXISTS public.ata_project_member (
  engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), user_id varchar(128) NOT NULL,
  role_code varchar(64) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (engagement_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_ata_project_member_user ON public.ata_project_member (user_id);

CREATE TABLE IF NOT EXISTS public.audit_report (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id),
  report_type varchar(64) NOT NULL, template_version varchar(64) NOT NULL, report_version integer NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'draft', fact_snapshot_json jsonb NOT NULL, artifact_ref text,
  created_by varchar(128) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (engagement_id, report_type, report_version)
);

CREATE TABLE IF NOT EXISTS public.ata_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor_user_id varchar(128) NOT NULL,
  engagement_id bigint REFERENCES public.audit_engagement(id), action varchar(128) NOT NULL, target_type varchar(64) NOT NULL,
  target_id varchar(128), request_id varchar(128), details_json jsonb, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ata_audit_log_engagement ON public.ata_audit_log (engagement_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ata_audit_log_actor ON public.ata_audit_log (actor_user_id, created_at);

CREATE TABLE IF NOT EXISTS public.annual_import_batch (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id),
  source_ref varchar(1024) NOT NULL, source_type varchar(64) NOT NULL, source_sha256 char(64), status varchar(32) NOT NULL DEFAULT 'pending',
  row_count integer NOT NULL DEFAULT 0 CHECK (row_count >= 0), metadata_json jsonb, error_message text, created_by varchar(128) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_annual_import_engagement ON public.annual_import_batch (engagement_id, source_type, status);

CREATE TABLE IF NOT EXISTS public.annual_account_balance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), import_batch_id bigint NOT NULL REFERENCES public.annual_import_batch(id),
  period_end date NOT NULL, account_code varchar(64) NOT NULL, account_name varchar(255) NOT NULL,
  opening_debit numeric(20,2) NOT NULL DEFAULT 0, opening_credit numeric(20,2) NOT NULL DEFAULT 0, period_debit numeric(20,2) NOT NULL DEFAULT 0, period_credit numeric(20,2) NOT NULL DEFAULT 0,
  closing_debit numeric(20,2) NOT NULL DEFAULT 0, closing_credit numeric(20,2) NOT NULL DEFAULT 0, currency char(3) NOT NULL DEFAULT 'CNY', source_locator_json jsonb,
  source_file_id bigint, source_page_id bigint, source_chunk_id char(64), locator_kind varchar(32) NOT NULL DEFAULT 'sheet_row', UNIQUE (import_batch_id, account_code, period_end)
);
CREATE INDEX IF NOT EXISTS idx_annual_account_engagement ON public.annual_account_balance (engagement_id, account_code, period_end);

CREATE TABLE IF NOT EXISTS public.annual_journal_entry_line (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), import_batch_id bigint NOT NULL REFERENCES public.annual_import_batch(id),
  voucher_date date NOT NULL, voucher_no varchar(128) NOT NULL, line_no integer NOT NULL CHECK (line_no >= 0), account_code varchar(64) NOT NULL, account_name varchar(255) NOT NULL,
  debit_amount numeric(20,2) NOT NULL DEFAULT 0, credit_amount numeric(20,2) NOT NULL DEFAULT 0, counterparty varchar(255), description varchar(1024), source_locator_json jsonb,
  source_file_id bigint, source_page_id bigint, source_chunk_id char(64), locator_kind varchar(32) NOT NULL DEFAULT 'sheet_row', UNIQUE (import_batch_id, voucher_no, line_no)
);
CREATE INDEX IF NOT EXISTS idx_annual_journal_engagement_date ON public.annual_journal_entry_line (engagement_id, voucher_date);
CREATE INDEX IF NOT EXISTS idx_annual_journal_voucher ON public.annual_journal_entry_line (engagement_id, voucher_no);

CREATE TABLE IF NOT EXISTS public.annual_receivable_item (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), import_batch_id bigint NOT NULL REFERENCES public.annual_import_batch(id),
  customer_name varchar(255) NOT NULL, document_no varchar(128), occurrence_date date, due_date date, balance numeric(20,2) NOT NULL, currency char(3) NOT NULL DEFAULT 'CNY',
  is_related_party boolean NOT NULL DEFAULT false, source_locator_json jsonb, source_file_id bigint, source_page_id bigint, source_chunk_id char(64), locator_kind varchar(32) NOT NULL DEFAULT 'sheet_row'
);
CREATE INDEX IF NOT EXISTS idx_annual_receivable_engagement ON public.annual_receivable_item (engagement_id, customer_name);
CREATE INDEX IF NOT EXISTS idx_annual_receivable_due ON public.annual_receivable_item (engagement_id, due_date);

CREATE TABLE IF NOT EXISTS public.annual_bank_transaction (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), import_batch_id bigint NOT NULL REFERENCES public.annual_import_batch(id),
  bank_account varchar(128) NOT NULL, transaction_date date NOT NULL, amount numeric(20,2) NOT NULL, direction varchar(16) NOT NULL, counterparty varchar(255), transaction_ref varchar(255), description varchar(1024), running_balance numeric(20,2), source_locator_json jsonb,
  source_file_id bigint, source_page_id bigint, source_chunk_id char(64), locator_kind varchar(32) NOT NULL DEFAULT 'sheet_row'
);
CREATE INDEX IF NOT EXISTS idx_annual_bank_engagement_date ON public.annual_bank_transaction (engagement_id, transaction_date);
CREATE INDEX IF NOT EXISTS idx_annual_bank_counterparty ON public.annual_bank_transaction (engagement_id, counterparty);
CREATE INDEX IF NOT EXISTS idx_annual_bank_amount ON public.annual_bank_transaction (engagement_id, amount);

CREATE TABLE IF NOT EXISTS public.annual_analysis_run (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), analysis_type varchar(64) NOT NULL, input_version varchar(128) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'running', parameters_json jsonb NOT NULL, result_json jsonb, created_by varchar(128) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_annual_analysis_engagement ON public.annual_analysis_run (engagement_id, analysis_type, created_at);

CREATE TABLE IF NOT EXISTS public.annual_finding (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), analysis_run_id bigint NOT NULL REFERENCES public.annual_analysis_run(id),
  finding_type varchar(64) NOT NULL, risk_level varchar(16) NOT NULL, title varchar(255) NOT NULL, description text NOT NULL, amount numeric(20,2), evidence_refs_json jsonb NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'open', created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_annual_finding_engagement ON public.annual_finding (engagement_id, risk_level, status);

CREATE TABLE IF NOT EXISTS public.annual_workpaper (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), workpaper_code varchar(64) NOT NULL, workpaper_name varchar(255) NOT NULL,
  template_version varchar(64) NOT NULL, workpaper_version integer NOT NULL, status varchar(32) NOT NULL DEFAULT 'draft', facts_json jsonb NOT NULL, conclusion_text text, artifact_ref text,
  created_by varchar(128) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (engagement_id, workpaper_code, workpaper_version)
);

CREATE TABLE IF NOT EXISTS public.annual_task (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), task_no varchar(64), action varchar(500) NOT NULL, detail text,
  assigned_role varchar(128), assigned_to varchar(128), deadline date, deliverable varchar(500), priority varchar(16) NOT NULL DEFAULT '中', source_engine varchar(64) NOT NULL DEFAULT 'annual_audit',
  status varchar(32) NOT NULL DEFAULT '待执行', completion_note text, started_at timestamptz, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_annual_task_engagement_status ON public.annual_task (engagement_id, status, deadline);
CREATE INDEX IF NOT EXISTS idx_annual_task_assignee ON public.annual_task (assigned_to, status);

CREATE TABLE IF NOT EXISTS public.annual_engagement_profile (
  engagement_id bigint PRIMARY KEY REFERENCES public.audit_engagement(id), profile_version integer NOT NULL DEFAULT 1 CHECK (profile_version >= 0), acceptance_status varchar(32) NOT NULL DEFAULT 'pending', independence_status varchar(32) NOT NULL DEFAULT 'pending',
  data_classification varchar(64), data_residency varchar(128), model_data_policy varchar(64), profile_json jsonb NOT NULL, created_by varchar(128) NOT NULL, updated_by varchar(128) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_annual_profile_gate ON public.annual_engagement_profile (acceptance_status, independence_status);

CREATE TABLE IF NOT EXISTS public.annual_audit_program_item (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), program_version varchar(64) NOT NULL, procedure_code varchar(64) NOT NULL,
  phase varchar(64) NOT NULL, cycle varchar(128) NOT NULL, procedure_name varchar(255) NOT NULL, assertions_json jsonb, risk_area varchar(255), required_material_categories_json jsonb,
  requires_evidence boolean NOT NULL DEFAULT true, status varchar(32) NOT NULL DEFAULT 'not_started', sample_plan_json jsonb, evidence_refs_json jsonb, exception_count integer NOT NULL DEFAULT 0 CHECK (exception_count >= 0),
  alternative_procedures_json jsonb, conclusion_text text, not_applicable_reason text, prepared_by varchar(128), prepared_at timestamptz, reviewed_by varchar(128), reviewed_at timestamptz,
  policy_binding_id bigint, revision integer NOT NULL DEFAULT 1 CHECK (revision >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (engagement_id, procedure_code)
);
CREATE INDEX IF NOT EXISTS idx_annual_program_status ON public.annual_audit_program_item (engagement_id, status, phase);

CREATE TABLE IF NOT EXISTS public.annual_audit_program_event (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), procedure_code varchar(64) NOT NULL, event_type varchar(64) NOT NULL,
  before_json jsonb, after_json jsonb, actor_user_id varchar(128) NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_annual_program_event ON public.annual_audit_program_event (engagement_id, procedure_code, created_at);

CREATE TABLE IF NOT EXISTS public.annual_confirmation (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), procedure_code varchar(64) NOT NULL, counterparty_name varchar(255) NOT NULL,
  confirmation_type varchar(64) NOT NULL, status varchar(32) NOT NULL DEFAULT 'planned', auditor_controlled_delivery boolean NOT NULL DEFAULT false, request_evidence_refs_json jsonb, response_evidence_refs_json jsonb,
  reliability_assessment text, exception_description text, alternative_procedures_json jsonb, conclusion_text text, prepared_by varchar(128), reviewed_by varchar(128), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_annual_confirmation ON public.annual_confirmation (engagement_id, procedure_code, status);

CREATE TABLE IF NOT EXISTS public.annual_finding_resolution (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), finding_id bigint NOT NULL UNIQUE REFERENCES public.annual_finding(id),
  resolution_status varchar(32) NOT NULL DEFAULT 'open', resolution_type varchar(64), resolution_note text, evidence_refs_json jsonb, resolved_by varchar(128), resolved_at timestamptz, reviewed_by varchar(128), reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_annual_finding_resolution ON public.annual_finding_resolution (engagement_id, resolution_status);

CREATE TABLE IF NOT EXISTS public.annual_review_decision (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), review_level varchar(32) NOT NULL, decision varchar(32) NOT NULL,
  decision_note text, scope_json jsonb, reviewer_user_id varchar(128) NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_annual_review_decision ON public.annual_review_decision (engagement_id, review_level, created_at);

CREATE TABLE IF NOT EXISTS public.annual_knowledge_document (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_code varchar(128) NOT NULL UNIQUE, title varchar(512) NOT NULL, authority_type varchar(32) NOT NULL,
  source_issuer varchar(255) NOT NULL, source_url varchar(2048), source_hash char(64), scope_json jsonb, status varchar(32) NOT NULL DEFAULT 'draft', created_by varchar(128) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (authority_type IN ('law','accounting_standard','auditing_standard','regulatory_guidance','firm_methodology','industry_guidance','case_reference'))
);
CREATE INDEX IF NOT EXISTS idx_annual_knowledge_document_status ON public.annual_knowledge_document (authority_type, status);

CREATE TABLE IF NOT EXISTS public.annual_knowledge_version (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, document_id bigint NOT NULL REFERENCES public.annual_knowledge_document(id), version_no integer NOT NULL CHECK (version_no >= 0),
  source_url varchar(2048) NOT NULL, source_hash char(64) NOT NULL, publication_date date, effective_from date, effective_to date, supersedes_version_id bigint REFERENCES public.annual_knowledge_version(id),
  content_text text NOT NULL, content_hash char(64) NOT NULL, review_status varchar(32) NOT NULL DEFAULT 'draft', reviewed_by varchar(128), reviewed_at timestamptz, approved_by varchar(128), approved_at timestamptz,
  change_summary text, created_by varchar(128) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (document_id, version_no)
);
CREATE INDEX IF NOT EXISTS idx_annual_knowledge_version_eligibility ON public.annual_knowledge_version (review_status, effective_from, effective_to);

CREATE TABLE IF NOT EXISTS public.annual_knowledge_chunk (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, knowledge_version_id bigint NOT NULL REFERENCES public.annual_knowledge_version(id), chunk_no integer NOT NULL CHECK (chunk_no >= 0),
  locator varchar(255), heading varchar(512), content_text text NOT NULL, content_hash char(64) NOT NULL, metadata_json jsonb, UNIQUE (knowledge_version_id, chunk_no)
);
CREATE INDEX IF NOT EXISTS idx_annual_knowledge_chunk_version ON public.annual_knowledge_chunk (knowledge_version_id);

CREATE TABLE IF NOT EXISTS public.annual_knowledge_release (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, release_code varchar(128) NOT NULL, release_version varchar(64) NOT NULL, status varchar(32) NOT NULL DEFAULT 'draft',
  effective_from date, effective_to date, approval_note text, approved_by varchar(128), approved_at timestamptz, created_by varchar(128) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (release_code, release_version)
);
CREATE INDEX IF NOT EXISTS idx_annual_knowledge_release_eligibility ON public.annual_knowledge_release (status, effective_from, effective_to);

CREATE TABLE IF NOT EXISTS public.annual_knowledge_release_item (
  release_id bigint NOT NULL REFERENCES public.annual_knowledge_release(id), knowledge_version_id bigint NOT NULL REFERENCES public.annual_knowledge_version(id),
  created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (release_id, knowledge_version_id)
);

CREATE TABLE IF NOT EXISTS public.annual_audit_ruleset (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ruleset_code varchar(128) NOT NULL, version varchar(64) NOT NULL, name varchar(255) NOT NULL, scope_json jsonb,
  status varchar(32) NOT NULL DEFAULT 'draft', effective_from date, effective_to date, approved_by varchar(128), approved_at timestamptz, created_by varchar(128) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (ruleset_code, version)
);
CREATE INDEX IF NOT EXISTS idx_annual_ruleset_eligibility ON public.annual_audit_ruleset (status, effective_from, effective_to);

CREATE TABLE IF NOT EXISTS public.annual_audit_rule (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ruleset_id bigint NOT NULL REFERENCES public.annual_audit_ruleset(id), rule_code varchar(128) NOT NULL, rule_type varchar(32) NOT NULL,
  name varchar(512) NOT NULL, authority_locator varchar(512), knowledge_version_id bigint REFERENCES public.annual_knowledge_version(id), applicability_json jsonb, preconditions_json jsonb,
  evidence_requirements_json jsonb, logic_json jsonb, exception_handling_json jsonb, status varchar(32) NOT NULL DEFAULT 'draft', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (ruleset_id, rule_code), CHECK (rule_type IN ('mandatory_requirement','firm_methodology','data_check','risk_signal'))
);
CREATE INDEX IF NOT EXISTS idx_annual_rule_type ON public.annual_audit_rule (ruleset_id, rule_type, status);

CREATE TABLE IF NOT EXISTS public.annual_engagement_policy_binding (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), knowledge_release_id bigint REFERENCES public.annual_knowledge_release(id),
  ruleset_id bigint REFERENCES public.annual_audit_ruleset(id), binding_status varchar(32) NOT NULL DEFAULT 'draft', reporting_period_date date NOT NULL, bound_by varchar(128), bound_at timestamptz,
  snapshot_json jsonb, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_annual_policy_binding ON public.annual_engagement_policy_binding (engagement_id, binding_status);

CREATE TABLE IF NOT EXISTS public.annual_release_gate (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), gate_status varchar(32) NOT NULL,
  blockers_json jsonb NOT NULL, snapshot_json jsonb NOT NULL, evaluated_by varchar(128) NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_annual_release_gate ON public.annual_release_gate (engagement_id, gate_status, created_at);

CREATE TABLE IF NOT EXISTS public.annual_audit_issuance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL UNIQUE REFERENCES public.audit_engagement(id), gate_id bigint NOT NULL REFERENCES public.annual_release_gate(id),
  report_artifact_ref varchar(2048) NOT NULL, report_artifact_sha256 char(64) NOT NULL, signing_attestation boolean NOT NULL DEFAULT false, signed_by varchar(128) NOT NULL, signed_at timestamptz NOT NULL,
  opinion_type varchar(64) NOT NULL, issuance_note text, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.annual_audit_archive (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL UNIQUE REFERENCES public.audit_engagement(id), issuance_id bigint NOT NULL REFERENCES public.annual_audit_issuance(id),
  archive_manifest_ref varchar(2048) NOT NULL, archive_manifest_sha256 char(64) NOT NULL, archive_completed_at timestamptz NOT NULL, retention_until date NOT NULL, archived_by varchar(128) NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.annual_report_citation_manifest (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), annual_report_id bigint NOT NULL REFERENCES public.audit_report(id),
  report_type varchar(64) NOT NULL, report_version integer NOT NULL, citation_id varchar(128) NOT NULL, section_key varchar(255) NOT NULL DEFAULT '', paragraph_key varchar(255) NOT NULL DEFAULT '',
  annual_finding_id bigint REFERENCES public.annual_finding(id), annual_finding_key char(64) NOT NULL, analysis_run_id bigint REFERENCES public.annual_analysis_run(id), analysis_type varchar(64), finding_type varchar(64), risk_level varchar(16),
  rule_metadata_json jsonb NOT NULL, finding_metadata_json jsonb NOT NULL, evidence_snapshot_json jsonb NOT NULL, anchor_status varchar(32) NOT NULL, snapshot_hash char(64) NOT NULL, final_report_ref varchar(1024),
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (engagement_id, report_type, report_version, citation_id), UNIQUE (engagement_id, annual_report_id, citation_id),
  FOREIGN KEY (engagement_id, report_type, report_version) REFERENCES public.audit_report(engagement_id, report_type, report_version),
  CHECK (anchor_status IN ('bound','partial','unbound','no_evidence'))
);
CREATE INDEX IF NOT EXISTS idx_annual_report_citation_finding ON public.annual_report_citation_manifest (engagement_id, annual_finding_id);
CREATE INDEX IF NOT EXISTS idx_annual_report_citation_finding_key ON public.annual_report_citation_manifest (engagement_id, annual_finding_key);
CREATE INDEX IF NOT EXISTS idx_annual_report_citation_analysis_run ON public.annual_report_citation_manifest (engagement_id, analysis_run_id);
CREATE INDEX IF NOT EXISTS idx_annual_report_citation_report_ref ON public.annual_report_citation_manifest (engagement_id, final_report_ref);

CREATE TABLE IF NOT EXISTS public.annual_report_citation_delivery_ref (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), annual_report_id bigint NOT NULL REFERENCES public.audit_report(id),
  report_type varchar(64) NOT NULL, report_version integer NOT NULL, final_report_ref varchar(1024) NOT NULL, final_report_ref_hash char(64) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (engagement_id, final_report_ref_hash), FOREIGN KEY (engagement_id, report_type, report_version) REFERENCES public.audit_report(engagement_id, report_type, report_version)
);
CREATE INDEX IF NOT EXISTS idx_annual_report_citation_delivery_version ON public.annual_report_citation_delivery_ref (engagement_id, annual_report_id, report_type, report_version);

CREATE TABLE IF NOT EXISTS public.annual_engagement_fact (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), fact_key varchar(191) NOT NULL, candidate_key varchar(191) NOT NULL,
  value_json jsonb NOT NULL, display_value text, data_type varchar(32) NOT NULL DEFAULT 'string', status varchar(32) NOT NULL DEFAULT 'candidate', source_kind varchar(64) NOT NULL,
  source_ref_json jsonb, evidence_refs_json jsonb, revision integer NOT NULL CHECK (revision >= 0), is_current boolean NOT NULL DEFAULT true,
  current_marker smallint GENERATED ALWAYS AS (CASE WHEN is_current THEN 1 ELSE NULL END) STORED, reviewed_by varchar(128), reviewed_at timestamptz, created_by varchar(128) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (engagement_id, fact_key, revision), UNIQUE (engagement_id, fact_key, candidate_key, current_marker),
  CHECK (status IN ('candidate','confirmed','conflicted','rejected'))
);
CREATE INDEX IF NOT EXISTS idx_annual_engagement_fact_status ON public.annual_engagement_fact (engagement_id, status, is_current);

CREATE TABLE IF NOT EXISTS public.annual_attachment_generation_job (
  id varchar(36) PRIMARY KEY, engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), report_id bigint NOT NULL REFERENCES public.audit_report(id), report_version integer NOT NULL,
  thread_id varchar(255), assistant_turn_id varchar(255), template_family_id varchar(36) NOT NULL, template_version_id varchar(36) NOT NULL, template_snapshot_json jsonb NOT NULL,
  template_content_sha256 char(64) NOT NULL, fact_snapshot_ref varchar(2048) NOT NULL, fact_snapshot_sha256 char(64) NOT NULL, input_fingerprint char(64) NOT NULL, request_idempotency_key_hash char(64),
  request_scope varchar(64) NOT NULL DEFAULT 'all_active_template_files', delivery_level varchar(32) NOT NULL DEFAULT 'review_draft', status varchar(32) NOT NULL DEFAULT 'queued', stage varchar(64) NOT NULL DEFAULT 'queued',
  progress smallint NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100), expected_item_count integer NOT NULL CHECK (expected_item_count >= 0), succeeded_item_count integer NOT NULL DEFAULT 0 CHECK (succeeded_item_count >= 0 AND succeeded_item_count <= expected_item_count),
  error_code varchar(64), error_summary varchar(1024), lease_token varchar(36), lease_expires_at timestamptz, model_manifest_json jsonb NOT NULL, renderer_manifest_json jsonb NOT NULL, requested_by varchar(128) NOT NULL,
  queued_at timestamptz NOT NULL DEFAULT now(), started_at timestamptz, completed_at timestamptz, cancelled_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now(),
  dedupe_fingerprint char(64) GENERATED ALWAYS AS (CASE WHEN status = 'cancelled' THEN NULL ELSE input_fingerprint END) STORED,
  UNIQUE (dedupe_fingerprint), UNIQUE (engagement_id, request_idempotency_key_hash),
  CHECK (status IN ('queued','running','succeeded','failed','cancelled')), CHECK (delivery_level IN ('review_draft','final_candidate','issued'))
);
CREATE INDEX IF NOT EXISTS idx_annual_attachment_job_fingerprint ON public.annual_attachment_generation_job (input_fingerprint);
CREATE INDEX IF NOT EXISTS idx_annual_attachment_job_case ON public.annual_attachment_generation_job (engagement_id, queued_at);
CREATE INDEX IF NOT EXISTS idx_annual_attachment_job_message ON public.annual_attachment_generation_job (thread_id, assistant_turn_id);

CREATE TABLE IF NOT EXISTS public.annual_attachment_generation_item (
  id varchar(36) PRIMARY KEY, job_id varchar(36) NOT NULL REFERENCES public.annual_attachment_generation_job(id), template_file_id varchar(36) NOT NULL, document_code varchar(128) NOT NULL,
  display_name varchar(255) NOT NULL, extension varchar(16) NOT NULL, source_template_sha256 char(64) NOT NULL, compiled_template_sha256 char(64) NOT NULL, binding_manifest_json jsonb NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'queued', stage varchar(64) NOT NULL DEFAULT 'queued', attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0), payload_ref varchar(2048), payload_sha256 char(64), quality_report_json jsonb,
  error_code varchar(64), error_summary varchar(1024), lease_token varchar(36), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (job_id, template_file_id), CHECK (status IN ('queued','running','succeeded','failed','cancelled'))
);
CREATE INDEX IF NOT EXISTS idx_annual_attachment_item_status ON public.annual_attachment_generation_item (job_id, status, stage);

CREATE TABLE IF NOT EXISTS public.annual_generated_artifact (
  id varchar(36) PRIMARY KEY, job_id varchar(36) NOT NULL REFERENCES public.annual_attachment_generation_job(id), item_id varchar(36) NOT NULL UNIQUE REFERENCES public.annual_attachment_generation_item(id),
  engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id), report_id bigint NOT NULL REFERENCES public.audit_report(id), template_version_id varchar(36) NOT NULL, template_file_id varchar(36) NOT NULL,
  document_code varchar(128) NOT NULL, display_name varchar(255) NOT NULL, file_name varchar(512) NOT NULL, extension varchar(16) NOT NULL, content_type varchar(255) NOT NULL, file_size bigint NOT NULL CHECK (file_size >= 0),
  sha256 char(64) NOT NULL, object_ref varchar(2048) NOT NULL, preview_ref varchar(2048), preview_sha256 char(64), provenance_manifest_ref varchar(2048) NOT NULL, provenance_sha256 char(64) NOT NULL,
  status varchar(32) NOT NULL DEFAULT 'internal', delivery_approved boolean NOT NULL DEFAULT false, delivery_level varchar(32) NOT NULL DEFAULT 'review_draft', supersedes_artifact_id varchar(36) REFERENCES public.annual_generated_artifact(id),
  created_by varchar(128) NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), published_by varchar(128), published_at timestamptz,
  CHECK (status IN ('internal','validated','published','rejected')), CHECK (delivery_level IN ('review_draft','final_candidate','issued'))
);
CREATE INDEX IF NOT EXISTS idx_annual_generated_artifact_job ON public.annual_generated_artifact (job_id, delivery_approved);
CREATE INDEX IF NOT EXISTS idx_annual_generated_artifact_case ON public.annual_generated_artifact (engagement_id, created_at);

CREATE TABLE IF NOT EXISTS public.annual_attachment_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job_id varchar(36) NOT NULL REFERENCES public.annual_attachment_generation_job(id), event_type varchar(64) NOT NULL DEFAULT 'attachment.generate',
  status varchar(32) NOT NULL DEFAULT 'pending', attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0), available_at timestamptz NOT NULL DEFAULT now(), published_at timestamptz,
  last_error varchar(1024), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (job_id, event_type), CHECK (status IN ('pending','publishing','published','failed'))
);
CREATE INDEX IF NOT EXISTS idx_annual_attachment_outbox_dispatch ON public.annual_attachment_outbox (status, available_at);

CREATE TABLE IF NOT EXISTS public.annual_artifact_access_event (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, artifact_id varchar(36) NOT NULL REFERENCES public.annual_generated_artifact(id), engagement_id bigint NOT NULL REFERENCES public.audit_engagement(id),
  purpose varchar(32) NOT NULL, actor_user_id varchar(128) NOT NULL, ticket_id varchar(36) NOT NULL UNIQUE, expires_at timestamptz NOT NULL, redeemed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (purpose IN ('download','preview'))
);
CREATE INDEX IF NOT EXISTS idx_annual_artifact_access ON public.annual_artifact_access_event (artifact_id, created_at);

CREATE TABLE IF NOT EXISTS public.annual_attachment_storage_object (
  storage_ref_hash char(64) PRIMARY KEY, storage_ref varchar(2048) NOT NULL, object_kind varchar(32) NOT NULL, content_sha256 char(64), management_scope varchar(32) NOT NULL DEFAULT 'legacy_unknown',
  retention_state varchar(32) NOT NULL DEFAULT 'active', retention_until timestamptz, unreferenced_at timestamptz, first_registered_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now(),
  CHECK (object_kind IN ('context','payload','artifact','preview','provenance')), CHECK (management_scope IN ('legacy_unknown','managed_exclusive')), CHECK (retention_state IN ('active','retained','reclaim_candidate','legal_hold'))
);
CREATE INDEX IF NOT EXISTS idx_annual_attachment_storage_reclamation ON public.annual_attachment_storage_object (management_scope, retention_state, retention_until);

CREATE TABLE IF NOT EXISTS public.annual_attachment_storage_reference (
  storage_ref_hash char(64) NOT NULL REFERENCES public.annual_attachment_storage_object(storage_ref_hash), owner_type varchar(32) NOT NULL, owner_id varchar(36) NOT NULL, owner_field varchar(32) NOT NULL,
  acquired_by varchar(128) NOT NULL DEFAULT 'migration', acquired_at timestamptz NOT NULL DEFAULT now(), released_by varchar(128), release_reason varchar(128), released_at timestamptz,
  PRIMARY KEY (storage_ref_hash, owner_type, owner_id, owner_field), CHECK (owner_type IN ('generation_job','generation_item','generated_artifact')), CHECK (owner_field IN ('context','payload','artifact','preview','provenance'))
);
CREATE INDEX IF NOT EXISTS idx_annual_attachment_storage_owner ON public.annual_attachment_storage_reference (owner_type, owner_id, released_at);

DROP TRIGGER IF EXISTS trg_audit_engagement_updated_at ON public.audit_engagement;
CREATE TRIGGER trg_audit_engagement_updated_at BEFORE UPDATE ON public.audit_engagement FOR EACH ROW EXECUTE FUNCTION public.annual_audit_set_updated_at();
DROP TRIGGER IF EXISTS trg_annual_task_updated_at ON public.annual_task;
CREATE TRIGGER trg_annual_task_updated_at BEFORE UPDATE ON public.annual_task FOR EACH ROW EXECUTE FUNCTION public.annual_audit_set_updated_at();
DROP TRIGGER IF EXISTS trg_annual_profile_updated_at ON public.annual_engagement_profile;
CREATE TRIGGER trg_annual_profile_updated_at BEFORE UPDATE ON public.annual_engagement_profile FOR EACH ROW EXECUTE FUNCTION public.annual_audit_set_updated_at();
DROP TRIGGER IF EXISTS trg_annual_program_item_updated_at ON public.annual_audit_program_item;
CREATE TRIGGER trg_annual_program_item_updated_at BEFORE UPDATE ON public.annual_audit_program_item FOR EACH ROW EXECUTE FUNCTION public.annual_audit_set_updated_at();
DROP TRIGGER IF EXISTS trg_annual_confirmation_updated_at ON public.annual_confirmation;
CREATE TRIGGER trg_annual_confirmation_updated_at BEFORE UPDATE ON public.annual_confirmation FOR EACH ROW EXECUTE FUNCTION public.annual_audit_set_updated_at();
DROP TRIGGER IF EXISTS trg_annual_finding_resolution_updated_at ON public.annual_finding_resolution;
CREATE TRIGGER trg_annual_finding_resolution_updated_at BEFORE UPDATE ON public.annual_finding_resolution FOR EACH ROW EXECUTE FUNCTION public.annual_audit_set_updated_at();
DROP TRIGGER IF EXISTS trg_annual_knowledge_document_updated_at ON public.annual_knowledge_document;
CREATE TRIGGER trg_annual_knowledge_document_updated_at BEFORE UPDATE ON public.annual_knowledge_document FOR EACH ROW EXECUTE FUNCTION public.annual_audit_set_updated_at();
DROP TRIGGER IF EXISTS trg_annual_audit_rule_updated_at ON public.annual_audit_rule;
CREATE TRIGGER trg_annual_audit_rule_updated_at BEFORE UPDATE ON public.annual_audit_rule FOR EACH ROW EXECUTE FUNCTION public.annual_audit_set_updated_at();
DROP TRIGGER IF EXISTS trg_annual_report_citation_manifest_updated_at ON public.annual_report_citation_manifest;
CREATE TRIGGER trg_annual_report_citation_manifest_updated_at BEFORE UPDATE ON public.annual_report_citation_manifest FOR EACH ROW EXECUTE FUNCTION public.annual_audit_set_updated_at();
DROP TRIGGER IF EXISTS trg_annual_attachment_job_updated_at ON public.annual_attachment_generation_job;
CREATE TRIGGER trg_annual_attachment_job_updated_at BEFORE UPDATE ON public.annual_attachment_generation_job FOR EACH ROW EXECUTE FUNCTION public.annual_audit_set_updated_at();
DROP TRIGGER IF EXISTS trg_annual_attachment_item_updated_at ON public.annual_attachment_generation_item;
CREATE TRIGGER trg_annual_attachment_item_updated_at BEFORE UPDATE ON public.annual_attachment_generation_item FOR EACH ROW EXECUTE FUNCTION public.annual_audit_set_updated_at();
DROP TRIGGER IF EXISTS trg_annual_attachment_outbox_updated_at ON public.annual_attachment_outbox;
CREATE TRIGGER trg_annual_attachment_outbox_updated_at BEFORE UPDATE ON public.annual_attachment_outbox FOR EACH ROW EXECUTE FUNCTION public.annual_audit_set_updated_at();

INSERT INTO public.ata_schema_migration (version, description)
VALUES ('annual_audit_postgres_v3', 'annual audit PostgreSQL baseline')
ON CONFLICT (version) DO UPDATE SET description = EXCLUDED.description;
